language: node_js
env:
  - NODE_ENV=travis
node_js:
  - "4.4"
  - "5.10"
  - "6.3"
sudo: false
cache:
  directories:
    - node_modules
before_script:
  - mysql -e 'create database shop;'
  - mysql -e 'create database blog;'
script:
  - npm run lint
  - npm test
  - npm run test-cov-html
after_success:
  - npm run coverage-report
